# Generated by Django 5.1.7 on 2025-07-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0001_initial'),
    ]

    operations = [
        # Drop foreign key constraints first
        migrations.RunSQL(
            "SET FOREIGN_KEY_CHECKS = 0;",
            reverse_sql="SET FOREIGN_KEY_CHECKS = 1;"
        ),
        # Drop all Skills tables
        migrations.RunSQL(
            "DROP TABLE IF EXISTS Skills_swaprequest;",
            reverse_sql=""
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS Skills_userskill;",
            reverse_sql=""
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS Skills_feedback;",
            reverse_sql=""
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS Skills_swap;",
            reverse_sql=""
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS Skills_userprofile;",
            reverse_sql=""
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS Skills_skill;",
            reverse_sql=""
        ),
        # Re-enable foreign key checks
        migrations.RunSQL(
            "SET FOREIGN_KEY_CHECKS = 1;",
            reverse_sql="SET FOREIGN_KEY_CHECKS = 0;"
        ),
    ]
