# Generated by Django 5.1.7 on 2025-07-12 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0003_auto_20250712_1510'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swap',
            name='offered_skill',
        ),
        migrations.RemoveField(
            model_name='swap',
            name='requested_skill',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='swap',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='swap',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='swap',
            name='skill_offered',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='swap',
            name='skill_requested',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='availability',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills_offered',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills_wanted',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='swap',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provided_swaps', to=settings.AUTH_USER_MODEL),
        ),
    ]
